import test from "node:test";
import assert from "node:assert/strict";
import { reviewClient } from "../src/vercel-review.js";

test("Gateway key selects Gateway endpoint and model even with a direct key present", () => {
  assert.deepEqual(reviewClient({ AI_GATEWAY_API_KEY: "gateway-test", OPENAI_API_KEY: "direct-test" }), { provider: "AI Gateway", key: "gateway-test", baseURL: "https://ai-gateway.vercel.sh/v1", model: "openai/gpt-5.5" });
});
test("direct OpenAI retains its endpoint and configurable model", () => {
  assert.deepEqual(reviewClient({ AI_GATEWAY_API_KEY: " ", OPENAI_API_KEY: "direct-test", OPENAI_MODEL: "chosen-model" }), { provider: "OpenAI", key: "direct-test", baseURL: "https://api.openai.com/v1", model: "chosen-model" });
});
test("absent model credentials preserve Box AI selection", () => {
  assert.equal(reviewClient({}), undefined);
});

import { assertReviewProvider } from "../src/vercel-review.js";
test("acceptance rejects a synchronized review generated by the wrong provider", () => {
  const event = (provider: string) => JSON.stringify({ stage: "review-synchronized", provider });
  assert.doesNotThrow(() => assertReviewProvider(event("AI Gateway"), "AI Gateway"));
  assert.throws(() => assertReviewProvider(event("OpenAI"), "AI Gateway"), /expected provider/);
  assert.throws(() => assertReviewProvider("DEMO_PASS", "AI Gateway"), /expected provider/);
});
